import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ru" | "de" | "ar" | "ur" | "hi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys and their values
const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.marketplace": "Marketplace",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.signin": "Sign In",
    "nav.joinnow": "Join Now",
    "nav.logout": "Logout",
    "marketplace.title": "Marketplace",
    "marketplace.subtitle": "Discover construction materials, furniture, and equipment from trusted sellers",
    "search.placeholder": "Search products, materials, equipment...",
    "filter.category": "Category",
    "filter.allCategories": "All Categories",
    "filter.priceRange": "Price Range",
    "filter.location": "Location",
    "filter.allLocations": "All Locations",
    "filter.sortBy": "Sort By",
    "filter.newest": "Newest First",
    "filter.priceLowHigh": "Price: Low to High",
    "filter.priceHighLow": "Price: High to Low",
    "filter.popular": "Most Popular",
    "filter.clearFilters": "Clear Filters",
    "filter.applyFilters": "Apply Filters",
    "filter.showing": "Showing {{count}} of {{total}} products",
    "product.viewDetails": "View Details",
    "product.requestQuote": "Request Quote",
    "product.addToFavorites": "Add to Favorites",
    "product.removeFromFavorites": "Remove from Favorites",
    "product.contactSeller": "Contact Seller",
    "product.sendMessage": "Send Message",
    "product.specifications": "Specifications",
    "product.availability": "Availability",
    "product.inStock": "In Stock",
    "product.delivery": "Delivery",
    "product.minimumOrder": "Minimum Order",
    "dashboard.title": "Dashboard",
    "dashboard.myProducts": "My Products",
    "dashboard.favorites": "Favorites",
    "dashboard.inquiries": "Inquiries",
    "dashboard.profile": "Profile",
    "dashboard.addProduct": "Add Product",
    "dashboard.totalProducts": "Total Products",
    "dashboard.activeProducts": "Active Products",
    "dashboard.totalInquiries": "Total Inquiries",
    "dashboard.recentInquiries": "Recent Inquiries",
    "role.buyer": "Buyer/Explorer",
    "role.seller": "Shop Owner/Company",
    "welcome.title": "Welcome to Luova Marketplace",
    "welcome.subtitle": "Connect with trusted suppliers and find quality construction materials, furniture, and equipment.",
    "welcome.getStarted": "Get Started",
    "error.unauthorized": "You are logged out. Logging in again...",
    "error.notFound": "Page not found",
    "error.serverError": "Something went wrong. Please try again.",
    "loadMore": "Load More Products",
    "units.perBag": "per bag",
    "units.perTon": "per ton",
    "units.perSqM": "per sq m",
    "categories.construction": "Construction Materials",
    "categories.furniture": "Furniture",
    "categories.lighting": "Lighting Equipment",
    "categories.tools": "Tools & Hardware",
    "categories.electrical": "Electrical Supplies",
    "tags.cement": "cement",
    "tags.construction": "construction",
    "tags.furniture": "furniture",
    "tags.office": "office",
    "tags.lighting": "lighting",
    "tags.led": "led",
    "tags.steel": "steel",
    "tags.dining": "dining",
    "tags.industrial": "industrial",
    "tags.tiles": "tiles",
    "tags.ceramic": "ceramic",
    "tags.livingRoom": "living room"
  },
  ru: {
    "nav.home": "Главная",
    "nav.marketplace": "Магазин",
    "nav.about": "О нас",
    "nav.contact": "Контакты",
    "nav.signin": "Войти",
    "nav.joinnow": "Присоединиться",
    "nav.logout": "Выйти",
    "marketplace.title": "Магазин",
    "marketplace.subtitle": "Откройте для себя строительные материалы, мебель и оборудование от надежных продавцов",
    "search.placeholder": "Поиск товаров, материалов, оборудования...",
    "filter.category": "Категория",
    "filter.allCategories": "Все категории",
    "filter.priceRange": "Диапазон цен",
    "filter.location": "Местоположение",
    "filter.allLocations": "Все локации",
    "filter.sortBy": "Сортировать по",
    "filter.newest": "Сначала новые",
    "filter.priceLowHigh": "Цена: от низкой к высокой",
    "filter.priceHighLow": "Цена: от высокой к низкой",
    "filter.popular": "Самые популярные",
    "filter.clearFilters": "Очистить фильтры",
    "filter.applyFilters": "Применить фильтры",
    "filter.showing": "Показано {{count}} из {{total}} товаров",
    "product.viewDetails": "Подробнее",
    "product.requestQuote": "Запросить цену",
    "product.addToFavorites": "В избранное",
    "product.removeFromFavorites": "Удалить из избранного",
    "product.contactSeller": "Связаться с продавцом",
    "product.sendMessage": "Отправить сообщение",
    "product.specifications": "Характеристики",
    "product.availability": "Наличие",
    "product.inStock": "В наличии",
    "product.delivery": "Доставка",
    "product.minimumOrder": "Минимальный заказ",
    "dashboard.title": "Панель управления",
    "dashboard.myProducts": "Мои товары",
    "dashboard.favorites": "Избранное",
    "dashboard.inquiries": "Запросы",
    "dashboard.profile": "Профиль",
    "dashboard.addProduct": "Добавить товар",
    "dashboard.totalProducts": "Всего товаров",
    "dashboard.activeProducts": "Активных товаров",
    "dashboard.totalInquiries": "Всего запросов",
    "dashboard.recentInquiries": "Последние запросы",
    "role.buyer": "Покупатель/Исследователь",
    "role.seller": "Владелец магазина/Компания",
    "welcome.title": "Добро пожаловать в Luova Marketplace",
    "welcome.subtitle": "Свяжитесь с надежными поставщиками и найдите качественные строительные материалы, мебель и оборудование.",
    "welcome.getStarted": "Начать",
    "error.unauthorized": "Вы вышли из системы. Повторный вход...",
    "error.notFound": "Страница не найдена",
    "error.serverError": "Что-то пошло не так. Попробуйте снова.",
    "loadMore": "Загрузить больше товаров"
  },
  de: {
    "nav.home": "Startseite",
    "nav.marketplace": "Marktplatz",
    "nav.about": "Über uns",
    "nav.contact": "Kontakt",
    "nav.signin": "Anmelden",
    "nav.joinnow": "Jetzt beitreten",
    "nav.logout": "Abmelden",
    "marketplace.title": "Marktplatz",
    "marketplace.subtitle": "Entdecken Sie Baumaterialien, Möbel und Geräte von vertrauenswürdigen Verkäufern",
    "search.placeholder": "Produkte, Materialien, Geräte suchen...",
    "filter.category": "Kategorie",
    "filter.allCategories": "Alle Kategorien",
    "filter.priceRange": "Preisspanne",
    "filter.location": "Standort",
    "filter.allLocations": "Alle Standorte",
    "filter.sortBy": "Sortieren nach",
    "filter.newest": "Neueste zuerst",
    "filter.priceLowHigh": "Preis: Niedrig zu Hoch",
    "filter.priceHighLow": "Preis: Hoch zu Niedrig",
    "filter.popular": "Am beliebtesten",
    "filter.clearFilters": "Filter löschen",
    "filter.applyFilters": "Filter anwenden",
    "filter.showing": "{{count}} von {{total}} Produkten angezeigt",
    "product.viewDetails": "Details anzeigen",
    "product.requestQuote": "Angebot anfordern",
    "product.addToFavorites": "Zu Favoriten hinzufügen",
    "product.removeFromFavorites": "Aus Favoriten entfernen",
    "product.contactSeller": "Verkäufer kontaktieren",
    "product.sendMessage": "Nachricht senden",
    "product.specifications": "Spezifikationen",
    "product.availability": "Verfügbarkeit",
    "product.inStock": "Auf Lager",
    "product.delivery": "Lieferung",
    "product.minimumOrder": "Mindestbestellung",
    "dashboard.title": "Dashboard",
    "dashboard.myProducts": "Meine Produkte",
    "dashboard.favorites": "Favoriten",
    "dashboard.inquiries": "Anfragen",
    "dashboard.profile": "Profil",
    "dashboard.addProduct": "Produkt hinzufügen",
    "dashboard.totalProducts": "Gesamtprodukte",
    "dashboard.activeProducts": "Aktive Produkte",
    "dashboard.totalInquiries": "Gesamtanfragen",
    "dashboard.recentInquiries": "Neueste Anfragen",
    "role.buyer": "Käufer/Erkunder",
    "role.seller": "Geschäftsinhaber/Unternehmen",
    "welcome.title": "Willkommen bei Luova Marketplace",
    "welcome.subtitle": "Verbinden Sie sich mit vertrauenswürdigen Lieferanten und finden Sie hochwertige Baumaterialien, Möbel und Geräte.",
    "welcome.getStarted": "Loslegen",
    "error.unauthorized": "Sie sind abgemeldet. Erneut anmelden...",
    "error.notFound": "Seite nicht gefunden",
    "error.serverError": "Etwas ist schief gelaufen. Bitte versuchen Sie es erneut.",
    "loadMore": "Mehr Produkte laden"
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.marketplace": "السوق",
    "nav.about": "من نحن",
    "nav.contact": "اتصل بنا",
    "nav.signin": "تسجيل الدخول",
    "nav.joinnow": "انضم الآن",
    "nav.logout": "تسجيل الخروج",
    "marketplace.title": "السوق",
    "marketplace.subtitle": "اكتشف مواد البناء والأثاث والمعدات من البائعين الموثوقين",
    "search.placeholder": "البحث عن المنتجات والمواد والمعدات...",
    "filter.category": "الفئة",
    "filter.allCategories": "جميع الفئات",
    "filter.priceRange": "نطاق السعر",
    "filter.location": "الموقع",
    "filter.allLocations": "جميع المواقع",
    "filter.sortBy": "ترتيب حسب",
    "filter.newest": "الأحدث أولاً",
    "filter.priceLowHigh": "السعر: من المنخفض إلى العالي",
    "filter.priceHighLow": "السعر: من العالي إلى المنخفض",
    "filter.popular": "الأكثر شعبية",
    "filter.clearFilters": "مسح المرشحات",
    "filter.applyFilters": "تطبيق المرشحات",
    "filter.showing": "عرض {{count}} من {{total}} منتجات",
    "product.viewDetails": "عرض التفاصيل",
    "product.requestQuote": "طلب عرض سعر",
    "product.addToFavorites": "إضافة إلى المفضلة",
    "product.removeFromFavorites": "إزالة من المفضلة",
    "product.contactSeller": "الاتصال بالبائع",
    "product.sendMessage": "إرسال رسالة",
    "product.specifications": "المواصفات",
    "product.availability": "التوفر",
    "product.inStock": "متوفر",
    "product.delivery": "التسليم",
    "product.minimumOrder": "الحد الأدنى للطلب",
    "dashboard.title": "لوحة التحكم",
    "dashboard.myProducts": "منتجاتي",
    "dashboard.favorites": "المفضلة",
    "dashboard.inquiries": "الاستفسارات",
    "dashboard.profile": "الملف الشخصي",
    "dashboard.addProduct": "إضافة منتج",
    "dashboard.totalProducts": "إجمالي المنتجات",
    "dashboard.activeProducts": "المنتجات النشطة",
    "dashboard.totalInquiries": "إجمالي الاستفسارات",
    "dashboard.recentInquiries": "الاستفسارات الحديثة",
    "role.buyer": "مشتري/مستكشف",
    "role.seller": "مالك المتجر/شركة",
    "welcome.title": "مرحباً بك في Luova Marketplace",
    "welcome.subtitle": "تواصل مع الموردين الموثوقين وابحث عن مواد البناء والأثاث والمعدات عالية الجودة.",
    "welcome.getStarted": "البدء",
    "error.unauthorized": "لقد تم تسجيل خروجك. تسجيل الدخول مرة أخرى...",
    "error.notFound": "الصفحة غير موجودة",
    "error.serverError": "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
    "loadMore": "تحميل المزيد من المنتجات"
  },
  ur: {
    "nav.home": "گھر",
    "nav.marketplace": "بازار",
    "nav.about": "ہمارے بارے میں",
    "nav.contact": "رابطہ",
    "nav.signin": "سائن ان",
    "nav.joinnow": "شامل ہوں",
    "nav.logout": "لاگ آؤٹ",
    "marketplace.title": "بازار",
    "marketplace.subtitle": "قابل اعتماد فروشوں سے تعمیراتی مواد، فرنیچر، اور آلات دریافت کریں",
    "search.placeholder": "پروڈکٹس، مواد، آلات تلاش کریں...",
    "filter.category": "قسم",
    "filter.allCategories": "تمام اقسام",
    "filter.priceRange": "قیمت کی حد",
    "filter.location": "مقام",
    "filter.allLocations": "تمام مقامات",
    "filter.sortBy": "ترتیب دیں",
    "filter.newest": "پہلے نیا",
    "filter.priceLowHigh": "قیمت: کم سے زیادہ",
    "filter.priceHighLow": "قیمت: زیادہ سے کم",
    "filter.popular": "سب سے مقبول",
    "filter.clearFilters": "فلٹرز صاف کریں",
    "filter.applyFilters": "فلٹرز لگائیں",
    "filter.showing": "{{total}} میں سے {{count}} پروڈکٹس دکھا رہا ہے",
    "product.viewDetails": "تفصیلات دیکھیں",
    "product.requestQuote": "قیمت کی درخواست",
    "product.addToFavorites": "پسندیدہ میں شامل کریں",
    "product.removeFromFavorites": "پسندیدہ سے ہٹائیں",
    "product.contactSeller": "فروش کنندہ سے رابطہ",
    "product.sendMessage": "پیغام بھیجیں",
    "product.specifications": "تفصیلات",
    "product.availability": "دستیابی",
    "product.inStock": "دستیاب",
    "product.delivery": "ڈیلیوری",
    "product.minimumOrder": "کم سے کم آرڈر",
    "dashboard.title": "ڈیش بورڈ",
    "dashboard.myProducts": "میرے پروڈکٹس",
    "dashboard.favorites": "پسندیدہ",
    "dashboard.inquiries": "استفسارات",
    "dashboard.profile": "پروفائل",
    "dashboard.addProduct": "پروڈکٹ شامل کریں",
    "dashboard.totalProducts": "کل پروڈکٹس",
    "dashboard.activeProducts": "فعال پروڈکٹس",
    "dashboard.totalInquiries": "کل استفسارات",
    "dashboard.recentInquiries": "حالیہ استفسارات",
    "role.buyer": "خریدار/تلاش کرنے والا",
    "role.seller": "دکان مالک/کمپنی",
    "welcome.title": "Luova Marketplace میں خوش آمدید",
    "welcome.subtitle": "قابل اعتماد سپلائرز سے جڑیں اور معیاری تعمیراتی مواد، فرنیچر، اور آلات تلاش کریں۔",
    "welcome.getStarted": "شروع کریں",
    "error.unauthorized": "آپ لاگ آؤٹ ہو گئے ہیں۔ دوبارہ لاگ ان کر رہے ہیں...",
    "error.notFound": "صفحہ نہیں ملا",
    "error.serverError": "کچھ غلط ہوا۔ برائے کرم دوبارہ کوشش کریں۔",
    "loadMore": "مزید پروڈکٹس لوڈ کریں"
  },
  hi: {
    "nav.home": "होम",
    "nav.marketplace": "बाजार",
    "nav.about": "हमारे बारे में",
    "nav.contact": "संपर्क",
    "nav.signin": "साइन इन",
    "nav.joinnow": "अभी शामिल हों",
    "nav.logout": "लॉगआउट",
    "marketplace.title": "बाजार",
    "marketplace.subtitle": "भरोसेमंद विक्रेताओं से निर्माण सामग्री, फर्नीचर और उपकरण खोजें",
    "search.placeholder": "उत्पाद, सामग्री, उपकरण खोजें...",
    "filter.category": "श्रेणी",
    "filter.allCategories": "सभी श्रेणियां",
    "filter.priceRange": "मूल्य सीमा",
    "filter.location": "स्थान",
    "filter.allLocations": "सभी स्थान",
    "filter.sortBy": "इसके अनुसार क्रमबद्ध करें",
    "filter.newest": "नया पहले",
    "filter.priceLowHigh": "मूल्य: कम से ज्यादा",
    "filter.priceHighLow": "मूल्य: ज्यादा से कम",
    "filter.popular": "सबसे लोकप्रिय",
    "filter.clearFilters": "फिल्टर साफ़ करें",
    "filter.applyFilters": "फिल्टर लागू करें",
    "filter.showing": "{{total}} में से {{count}} उत्पाद दिखाए जा रहे हैं",
    "product.viewDetails": "विवरण देखें",
    "product.requestQuote": "कोटेशन का अनुरोध",
    "product.addToFavorites": "पसंदीदा में जोड़ें",
    "product.removeFromFavorites": "पसंदीदा से हटाएं",
    "product.contactSeller": "विक्रेता से संपर्क करें",
    "product.sendMessage": "संदेश भेजें",
    "product.specifications": "विशेषताएं",
    "product.availability": "उपलब्धता",
    "product.inStock": "स्टॉक में",
    "product.delivery": "वितरण",
    "product.minimumOrder": "न्यूनतम ऑर्डर",
    "dashboard.title": "डैशबोर्ड",
    "dashboard.myProducts": "मेरे उत्पाद",
    "dashboard.favorites": "पसंदीदा",
    "dashboard.inquiries": "पूछताछ",
    "dashboard.profile": "प्रोफाइल",
    "dashboard.addProduct": "उत्पाद जोड़ें",
    "dashboard.totalProducts": "कुल उत्पाद",
    "dashboard.activeProducts": "सक्रिय उत्पाद",
    "dashboard.totalInquiries": "कुल पूछताछ",
    "dashboard.recentInquiries": "हाल की पूछताछ",
    "role.buyer": "खरीदार/एक्सप्लोरर",
    "role.seller": "दुकान मालिक/कंपनी",
    "welcome.title": "Luova Marketplace में आपका स्वागत है",
    "welcome.subtitle": "भरोसेमंद आपूर्तिकर्ताओं से जुड़ें और गुणवत्तापूर्ण निर्माण सामग्री, फर्नीचर और उपकरण खोजें।",
    "welcome.getStarted": "शुरू करें",
    "error.unauthorized": "आप लॉग आउट हो गए हैं। फिर से लॉग इन कर रहे हैं...",
    "error.notFound": "पृष्ठ नहीं मिला",
    "error.serverError": "कुछ गलत हुआ। कृपया फिर से कोशिश करें।",
    "loadMore": "अधिक उत्पाद लोड करें"
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string, params?: Record<string, string>) => {
    let translation = translations[language][key] || translations.en[key] || key;
    
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        translation = translation.replace(new RegExp(`{{${param}}}`, 'g'), value);
      });
    }
    
    return translation;
  };

  const contextValue: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
